name: .NET

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ../../hackaton-lambda
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: us-east-2

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.x
            - name: AWS CLI
              run: dotnet tool install -g Amazon.Lambda.Tools
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Deploy to Lambda
              run: dotnet lambda deploy-serverless
