name: Publish AWS Lambda
on:
    push:
        branches:
            - dev
jobs:
    publish_lambda:
        name: Publish Lambda Function
        runs-on: ubuntu-latest
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "6.0.x" # ou '5.x' dependendo da versão que você está utilizando
            - name: Restore dependencies
              run: dotnet restore
            - name: Build project
              run: dotnet build -c Release
            - name: Publish Lambda package
              run: dotnet lambda package --configuration Release --output-package bin/release/net6.0/EnviarEmail.zip
            - name: Deploy Lambda function
              uses: aws-actions/aws-lambda-deploy@v0.2.0
              with:
                  args: dotnet lambda deploy-function EnviarEmail --function-role arn:aws:iam::190197150713:role/lambda-role --region us-east-2 --package bin/release/net6.0/EnviarEmail.zip
